# Generated by Django 5.1.4 on 2025-01-16 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_alter_project_project_workers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("note", models.TextField(blank=True, null=True)),
                ("event_date", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MEETING", "Meeting"),
                            ("RECEIVE", "Receive Devices or Documentation"),
                            ("DELIVER", "Delivery of Results"),
                            ("MILESTONE", "Milestone Achieved"),
                            ("KICKOFF", "Kickoff Meeting"),
                            ("UPDATE", "Progress Update"),
                            ("INCIDENT", "Incident Report"),
                            ("RETURN", "Return of Test Devices"),
                            ("REPORT", "Report Sent"),
                            ("FEEDBACK", "Post-Engagement Feedback"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "related_files",
                    models.FileField(blank=True, null=True, upload_to="event_files/"),
                ),
                (
                    "external_participants",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "action_creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
                (
                    "team_participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="team_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
