# Generated by Django 5.1.4 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="event_files/")),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="related_files",
        ),
        migrations.AddField(
            model_name="event",
            name="related_files",
            field=models.ManyToManyField(blank=True, to="events.file"),
        ),
    ]
