# Generated by Django 5.1.4 on 2025-01-17 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_file_remove_event_related_files_event_related_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEETING", "Meeting"),
                    ("RECEIVE", "Receive Devices or Documentation"),
                    ("DELIVER", "Delivery of Results"),
                    ("MILESTONE", "Milestone Achieved"),
                    ("KICKOFF", "Kickoff Meeting"),
                    ("UPDATE", "Progress Update"),
                    ("INCIDENT", "Incident Report"),
                    ("RETURN", "Return of Test Devices"),
                    ("REPORT", "Report Sent"),
                    ("FEEDBACK", "Post-Engagement Feedback"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
                null=True,
            ),
        ),
    ]
