# Generated by Django 5.1.4 on 2025-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_description_alter_event_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="related_files",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.file"
            ),
        ),
    ]
