# Generated by Django 5.1.4 on 2025-01-16 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="manufacturer",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("sa", "Security Assessment"), ("pt", "Pentest")],
                default="sa",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_workers",
            field=models.ManyToManyField(
                related_name="assigned_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vendor",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proj",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
