# Generated by Django 5.1.5 on 2025-01-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "employer_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "work_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etst", "Emerging technology Security testing"),
                            ("wsst", "wireless systems security testing"),
                            ("rts", "research and technical solutions"),
                            ("ai", "AI Security research"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
