# Generated by Django 5.1.4 on 2025-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_related_files"),
        ("tasks", "0002_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="files",
            field=models.ManyToManyField(related_name="tasks", to="events.file"),
        ),
    ]
