# Generated by Django 5.1.4 on 2025-01-19 10:42

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_related_files"),
        ("tasks", "0003_task_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(default=tasks.models.get_default_due_date),
        ),
        migrations.AlterField(
            model_name="task",
            name="files",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to="events.file"
            ),
        ),
    ]
