# Generated by Django 5.1.4 on 2025-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_alter_file_file_type"),
        ("tasks", "0005_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="files",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to="files.file"
            ),
        ),
    ]
