# Generated by Django 5.1.4 on 2025-01-19 20:06

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_task_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=tasks.models.get_default_due_date),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
