# Generated by Django 5.1.4 on 2025-01-18 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_rename_created_at_file_uploaded_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="file",
            name="confidentiality_level",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file_status",
        ),
        migrations.RemoveField(
            model_name="file",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="file",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="file",
            name="related_vulnerabilities",
        ),
        migrations.RemoveField(
            model_name="file",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="file",
            name="uploaded_by",
        ),
    ]
