# Generated by Django 5.1.4 on 2025-01-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_rename_uploaded_at_file_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="confidentiality_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="file_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Analysis"),
                    ("in_progress", "In Progress"),
                    ("completed", "Analysis Completed"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("external", "External Entity"),
                    ("exported", "Exported During Pentest"),
                    ("result", "Result of the Test"),
                    ("reply", "Document Reply"),
                    ("letter", "Letter"),
                    ("firmware", "Firmware"),
                    ("log", "Log File"),
                    ("exploit", "Exploit Script/Code"),
                    ("configuration", "Configuration File"),
                ],
                default="external",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="file",
            name="related_vulnerabilities",
            field=models.TextField(
                blank=True,
                help_text="IDs or names of related vulnerabilities",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for categorization",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
