# Generated by Django 5.1.4 on 2025-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_alter_file_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("external", "External Entity"),
                    ("exported", "Exported During Pentest"),
                    ("result", "Result of the Test"),
                    ("reply", "Document Reply"),
                    ("letter", "Letter"),
                    ("firmware", "Firmware"),
                    ("log", "Log File"),
                    ("exploit", "Exploit Script/Code"),
                    ("configuration", "Configuration File"),
                    ("tool", "Tool"),
                    ("other", "Other"),
                    ("writeup", "Writeup Related"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
