# Generated by Django 5.1.4 on 2025-01-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0005_alter_file_file_type"),
        ("projects", "0003_alter_project_project_workers"),
        ("tasks", "0007_alter_task_created_at_alter_task_due_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Writeup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writeups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="writeups_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_files",
                    models.ManyToManyField(
                        blank=True, related_name="writeups", to="files.file"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writeups",
                        to="projects.project",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="writeups", to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
