# Generated by Django 5.1.4 on 2025-01-20 21:18

import easymde.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("writeups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeup",
            name="content",
            field=easymde.fields.EasyMDEField(
                blank=True, null=True, verbose_name="mardown content"
            ),
        ),
    ]
