# Generated by Django 5.1.4 on 2025-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeups", "0002_alter_writeup_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="writeup",
            name="findings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
