# Generated by Django 5.1.4 on 2025-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writeups", "0003_writeup_description_writeup_findings"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeup",
            name="created_by",
            field=models.CharField(
                choices=[("file_upload", "File Upload"), ("editor", "Editor")],
                default="file_upload",
                max_length=20,
            ),
        ),
    ]
